name: veris744
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  video_player: ^2.8.0
  video_player_web: ^2.0.16 
  flutter_svg: ^2.0.7
  chewie: ^1.4.0
  url_launcher: ^6.0.10
  scrollable_positioned_list: ^0.3.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/videos/
    - assets/images/
